### ISSUE TITLE
Deploy script for github pages

### ISSUE THREAD

**Issue by adborden** [caciviclab/disclosure-frontend-alpha#24]
In the short-term, we should host this repo on github pages. This [gist](https://gist.github.com/domenic/ec8b0fc8ab45f39403dd) explains the how to use travis to run a deploy step to push to github pages. However, we'll want to make a few modifications.

- [x] Split the gulp build task in two, one to start the server and the second to build the project.
- [x] Configure travis with a github deploy key.
- [x] Run the new gulp build step as part of travis' after test hook.

**Comment by adborden** [comment]
Additional notes, frontend team is using the develop branch for development, so the script should only trigger deploy on the master branch.

**Comment by tdooner** [comment]
Hey @adborden, @jnmarcus and I were just browsing around the GH pages site and noticed that there is no server-side support for URLs we change via `pushState`.

I guess we could hack it on GH pages by creating stub pages for URLs that we know about... or use URL fragments instead of pushState... but really I think we will all be happier with a web server that has URL rewriting logic like mod_rewrite or ngx_http_rewrite_module.

**Comment by tdooner** [comment]
...so I'm going to create an issue for that, since we probably should get that down sooner rather than later.

**Comment by adborden** [comment]
Oh bummer! I'm not going to stop anyone from doing that work, but I'd rather not think about it right now and just use URL fragments for v1.

**Comment by adborden** [comment]
The work for this was merged, and we added pushState in https://github.com/caciviclab/disclosure-frontend-alpha/pull/35 , closing.
